[2024-09-03T17:43:52.739+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:43:52.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:43:52.744+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:43:52.743+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:43:53.055+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:43:53.051+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:43:53.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:43:53.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.433 seconds
[2024-09-03T17:44:23.914+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:44:23.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:44:23.919+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:23.919+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:44:24.053+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:24.048+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:44:24.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:44:24.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.220 seconds
[2024-09-03T17:44:54.183+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:44:54.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:44:54.189+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:54.188+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:44:54.321+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:44:54.317+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:44:54.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:44:54.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.214 seconds
[2024-09-03T17:45:24.683+0000] {processor.py:186} INFO - Started process (PID=226) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:45:24.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:45:24.689+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:45:24.688+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:45:24.812+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:45:24.808+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:45:24.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:45:24.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.215 seconds
[2024-09-03T17:45:55.007+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:45:55.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:45:55.011+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:45:55.011+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:45:55.162+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:45:55.158+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:45:55.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:45:55.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.239 seconds
[2024-09-03T17:46:25.318+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:46:25.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:46:25.322+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:25.321+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:46:25.429+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:25.424+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:46:25.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:46:25.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.333 seconds
[2024-09-03T17:46:56.406+0000] {processor.py:186} INFO - Started process (PID=274) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:46:56.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:46:56.410+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:56.410+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:46:56.713+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:46:56.706+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:46:56.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:46:56.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.400 seconds
[2024-09-03T17:47:27.106+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:47:27.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:47:27.111+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:27.111+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:47:27.462+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:27.458+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:47:27.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:47:27.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.446 seconds
[2024-09-03T17:47:57.842+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:47:57.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:47:57.848+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:57.848+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:47:58.220+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:47:58.215+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T17:47:58.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:47:58.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.453 seconds
[2024-09-03T17:48:03.156+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:48:03.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:48:03.165+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:03.164+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:48:03.534+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:03.531+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:48:03.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:48:03.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.469 seconds
[2024-09-03T17:48:34.348+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:48:34.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:48:34.353+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:34.352+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:48:34.650+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:48:34.647+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:48:34.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:48:34.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.372 seconds
[2024-09-03T17:49:05.000+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:49:05.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:49:05.005+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:05.005+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:49:05.369+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:05.327+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:49:05.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:49:05.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.453 seconds
[2024-09-03T17:49:35.537+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:49:35.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:49:35.542+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:35.541+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:49:35.818+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:49:35.814+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:49:35.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:49:35.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.364 seconds
[2024-09-03T17:50:06.037+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:50:06.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:50:06.040+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:06.040+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:50:06.301+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:06.297+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:50:06.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:50:06.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.331 seconds
[2024-09-03T17:50:36.968+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:50:36.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:50:36.973+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:36.972+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:50:37.222+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:50:37.219+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:50:37.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:50:37.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.322 seconds
[2024-09-03T17:51:07.570+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:51:07.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:51:07.575+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:07.574+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:51:07.890+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:07.886+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:51:07.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:51:07.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.395 seconds
[2024-09-03T17:51:38.209+0000] {processor.py:186} INFO - Started process (PID=423) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:51:38.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:51:38.213+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:38.213+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:51:38.481+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:51:38.477+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:51:38.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:51:38.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.356 seconds
[2024-09-03T17:52:08.851+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:52:08.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:52:08.855+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:08.855+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:52:09.107+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:09.102+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:52:09.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:52:09.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.324 seconds
[2024-09-03T17:52:39.448+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:52:39.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:52:39.452+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:39.452+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:52:39.708+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:52:39.704+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:52:39.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:52:39.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.336 seconds
[2024-09-03T17:53:10.022+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:53:10.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:53:10.027+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:10.027+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:53:10.293+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:10.290+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:53:10.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:53:10.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.351 seconds
[2024-09-03T17:53:41.065+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:53:41.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:53:41.069+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:41.068+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:53:41.294+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:53:41.291+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:53:41.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:53:41.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.289 seconds
[2024-09-03T17:54:11.562+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:54:11.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:54:11.566+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:11.565+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:54:11.896+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:11.892+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:54:11.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:54:11.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.411 seconds
[2024-09-03T17:54:42.623+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:54:42.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:54:42.628+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:42.628+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:54:42.917+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:54:42.912+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:54:42.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:54:42.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.355 seconds
[2024-09-03T17:55:13.244+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:55:13.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:55:13.248+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:13.248+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:55:13.534+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:13.530+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:55:13.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:55:13.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.368 seconds
[2024-09-03T17:55:43.894+0000] {processor.py:186} INFO - Started process (PID=551) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:55:43.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:55:43.899+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:43.898+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:55:44.164+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:55:44.160+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:55:44.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:55:44.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.344 seconds
[2024-09-03T17:56:14.427+0000] {processor.py:186} INFO - Started process (PID=567) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:56:14.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:56:14.430+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:14.430+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:56:14.665+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:14.661+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:56:14.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:56:14.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.303 seconds
[2024-09-03T17:56:44.822+0000] {processor.py:186} INFO - Started process (PID=583) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:56:44.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:56:44.825+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:44.825+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:56:45.069+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:56:45.066+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:56:45.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:56:45.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.331 seconds
[2024-09-03T17:57:15.745+0000] {processor.py:186} INFO - Started process (PID=599) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:57:15.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:57:15.749+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:15.748+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:57:15.990+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:15.985+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:57:15.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:57:16.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.390 seconds
[2024-09-03T17:57:46.408+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:57:46.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:57:46.412+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:46.412+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:57:46.715+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:57:46.712+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:57:46.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:57:46.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.383 seconds
[2024-09-03T17:58:17.064+0000] {processor.py:186} INFO - Started process (PID=631) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:58:17.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:58:17.067+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:17.067+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:58:17.310+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:17.306+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:58:17.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:58:17.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.328 seconds
[2024-09-03T17:58:47.649+0000] {processor.py:186} INFO - Started process (PID=647) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:58:47.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:58:47.652+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:47.652+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:58:47.917+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:58:47.913+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:58:47.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:58:47.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.348 seconds
[2024-09-03T17:59:18.237+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:59:18.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:59:18.240+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:59:18.240+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:59:18.553+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:59:18.548+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:59:18.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:59:18.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.391 seconds
[2024-09-03T17:59:49.004+0000] {processor.py:186} INFO - Started process (PID=679) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:59:49.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T17:59:49.009+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:59:49.009+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:59:49.119+0000] {logging_mixin.py:190} INFO - [2024-09-03T17:59:49.116+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T17:59:49.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T17:59:49.194+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.197 seconds
[2024-09-03T18:00:19.531+0000] {processor.py:186} INFO - Started process (PID=695) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:00:19.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:00:19.536+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:19.535+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:00:19.714+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:19.706+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:00:19.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:00:19.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.289 seconds
[2024-09-03T18:00:50.073+0000] {processor.py:186} INFO - Started process (PID=711) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:00:50.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:00:50.077+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:50.076+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:00:50.192+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:00:50.187+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:00:50.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:00:50.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.212 seconds
[2024-09-03T18:01:20.728+0000] {processor.py:186} INFO - Started process (PID=727) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:01:20.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:01:20.737+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:20.736+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:01:20.872+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:20.868+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:01:20.873+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:01:20.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.271 seconds
[2024-09-03T18:01:51.050+0000] {processor.py:186} INFO - Started process (PID=743) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:01:51.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:01:51.054+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:51.053+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:01:51.186+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:01:51.181+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:01:51.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:01:51.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.224 seconds
[2024-09-03T18:02:21.538+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:02:21.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:02:21.543+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:21.543+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:02:21.648+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:21.643+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:02:21.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:02:21.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.182 seconds
[2024-09-03T18:02:52.027+0000] {processor.py:186} INFO - Started process (PID=775) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:02:52.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:02:52.031+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:52.031+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:02:52.130+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:02:52.126+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:02:52.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:02:52.194+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.176 seconds
[2024-09-03T18:03:22.462+0000] {processor.py:186} INFO - Started process (PID=791) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:03:22.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:03:22.466+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:22.465+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:03:22.558+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:22.554+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:03:22.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:03:22.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.170 seconds
[2024-09-03T18:03:52.998+0000] {processor.py:186} INFO - Started process (PID=807) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:03:52.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:03:53.002+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:53.002+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:03:53.127+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:03:53.124+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:03:53.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:03:53.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.202 seconds
[2024-09-03T18:04:23.458+0000] {processor.py:186} INFO - Started process (PID=823) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:04:23.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:04:23.461+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:23.461+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:04:23.602+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:23.598+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:04:23.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:04:23.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.215 seconds
[2024-09-03T18:04:53.961+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:04:53.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:04:53.965+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:53.965+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:04:54.088+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:04:54.085+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:04:54.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:04:54.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.217 seconds
[2024-09-03T18:05:24.430+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:05:24.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:05:24.434+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:24.433+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:05:24.537+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:24.532+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:05:24.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:05:24.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.171 seconds
[2024-09-03T18:05:54.878+0000] {processor.py:186} INFO - Started process (PID=871) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:05:54.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:05:54.882+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:54.882+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:05:54.989+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:05:54.984+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:05:54.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:05:55.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.209 seconds
[2024-09-03T18:06:25.365+0000] {processor.py:186} INFO - Started process (PID=887) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:06:25.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T18:06:25.368+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:06:25.368+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:06:25.485+0000] {logging_mixin.py:190} INFO - [2024-09-03T18:06:25.481+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'post_string'
[2024-09-03T18:06:25.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T18:06:25.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.191 seconds
